[database]
database_host = localhost
database_name = airflow_reddit
database_port = 5432
database_username = postgres
database_password = postrgres

[file_paths]
input_path = /opt/airflow/data/input
output_path = /opt/airflow/data/output

[api_keys]
reddit_secret_key = oWfkY_ydRTt3y0JXcl2oFXEguy_zJg
reddit_client_id = 7yurXziHTm0E31IQ6ZoZIQ

[aws]
aws_access_key_id = AKIAQ5DB65RJMTIWTK4J
aws_secret_access_key= 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

aws_session_token= FwoGZXIvYXdzEAUaDE5nLQ1A+qm2jW1bBSKCAaIps0sOcpdIDXcUF3HEAf8rv6/l1M0H/cdaCtoV9BpY7uLoRRNUA+Vw0J2XbA78s++vH66hH4IJobPXSIsGS9M1SAESKMhg0qPCFk9MYhrDA1AR69rzSW4ZFBzQf2P0bpsEX1OemsNJsOELh+3/5clo9XVEhaXHC2XnZaj/UINoyNYo+7eQvAYyKPrn15jEdzF
aws_region = us-east-2
aws_bucket_name = redditetl

[etl_settings]
batch_size = 100
error_handling = abort
log_level = info